# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1407, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/navi_png/vps主机.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-fuzhi-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pic/op_png/ques.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgba(167, 162, 157,100);\n"
                                         "    border: none; /* 无边框 */\n"
                                         "    padding: 10px 20px; /* 内边距 */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font: 16pt \"黑体\";\n"
                                         "    margin: 4px 2px;\n"
                                         "    cursor: pointer;\n"
                                         "    border-radius: 10px; /* 圆角 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                         "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-bianji／xiugai.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-pizhuxinxi-solid.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-shezhi-solid.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgba(167, 162, 157,100);\n"
                                      "    border: none; /* 无边框 */\n"
                                      "    padding: 10px 20px; /* 内边距 */\n"
                                      "    text-align: center;\n"
                                      "    text-decoration: none;\n"
                                      "    font: 16pt \"黑体\";\n"
                                      "    margin: 4px 2px;\n"
                                      "    cursor: pointer;\n"
                                      "    border-radius: 10px; /* 圆角 */\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                      "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("pic/navi_png/icon-initiate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.in_or_out = QtWidgets.QWidget()
        self.in_or_out.setObjectName("in_or_out")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.in_or_out)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.in_or_out)
        self.label.setStyleSheet("font: 14pt \"等线\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.in_or_out)
        self.lineEdit.setStyleSheet("QWidget {\n"
                                    "    background-color: rgba(229, 229, 229, 180); \n"
                                    "    border: 1px solid #ccc; /* 边框 */\n"
                                    "    border-radius: 10px; /* 圆角半径 */\n"
                                    "    padding: 10px; /* 内边距 */\n"
                                     
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.in_or_out)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-you2-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.in_or_out)
        self.textBrowser.setStyleSheet("QWidget {\n"
                                       "    background-color: rgba(229, 229, 229, 180); \n"
                                       "    border: 1px solid #ccc; /* 边框 */\n"
                                       "    border-radius: 10px; /* 圆角半径 */\n"
                                       "    padding: 10px; /* 内边距 */\n"
                                       "    font: 75 14pt \"Microsoft YaHei \";\n"
                                       "}")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.in_or_out)
        self.label_2.setStyleSheet("font: 14pt \"等线\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.in_or_out)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-zuo2-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon8)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.in_or_out)
        self.lineEdit_2.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 10px; /* 内边距 */\n"
                                       
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.in_or_out)
        self.textBrowser_2.setStyleSheet("QWidget {\n"
                                         "    background-color: rgba(229, 229, 229, 180); \n"
                                         "    border: 1px solid #ccc; /* 边框 */\n"
                                         "    border-radius: 10px; /* 圆角半径 */\n"
                                         "    padding: 10px; /* 内边距 */\n"
                                         "    font: 75 14pt \"Microsoft YaHei \";\n"
                                         "}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 1, 0, 1, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 2, 1)
        self.widget_3 = QtWidgets.QWidget(self.in_or_out)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(80, 120, 400, 400))
        self.label_3.setStyleSheet("QWidget {\n"
                                   "   background-color: rgba(250, 229, 229, 180); \n"
                                   "    border: 1px solid #ccc; /* 边框 */\n"
                                   "    border-radius: 10px; /* 圆角半径 */\n"
                                   "    padding: 10px; /* 内边距 */\n"
                                   "}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(0, 610, 548, 61))
        self.label_4.setStyleSheet("    font: 16pt \"黑体\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 540, 271, 51))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 10pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("pic/op_png/referh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon9)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.widget_3, 0, 1, 2, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 2)
        self.gridLayout_3.setColumnMinimumWidth(1, 1)
        self.gridLayout_3.setRowMinimumHeight(0, 1)
        self.gridLayout_3.setRowMinimumHeight(1, 2)
        self.gridLayout_3.setRowMinimumHeight(2, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.in_or_out)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.label_14 = QtWidgets.QLabel(self.setting)
        self.label_14.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label_14.setObjectName("label_14")
        self.comboBox_9 = QtWidgets.QComboBox(self.setting)
        self.comboBox_9.setGeometry(QtCore.QRect(50, 110, 98, 38))
        self.comboBox_9.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.setting)
        self.comboBox_10.setGeometry(QtCore.QRect(200, 110, 131, 38))
        self.comboBox_10.setStyleSheet("QWidget {\n"
                                       "    background-color: rgba(229, 229, 229, 180); \n"
                                       "    border: 1px solid #ccc; /* 边框 */\n"
                                       "    border-radius: 10px; /* 圆角半径 */\n"
                                       "    padding: 5px; /* 内边距 */\n"
                                      
                                       "}")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.stackedWidget.addWidget(self.setting)
        self.data = QtWidgets.QWidget()
        self.data.setObjectName("data")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.data)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.data)
        self.comboBox_2.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.data)
        self.comboBox.setStyleSheet("QWidget {\n"
                                    "    background-color: rgba(229, 229, 229, 180); \n"
                                    "    border: 1px solid #ccc; /* 边框 */\n"
                                    "    border-radius: 10px; /* 圆角半径 */\n"
                                    "    padding: 5px; /* 内边距 */\n"
                                   
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.data)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgba(167, 162, 157,100);\n"
                                         "    border: none; /* 无边框 */\n"
                                         "    padding: 10px 20px; /* 内边距 */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font: 12pt \"黑体\";\n"
                                         "    margin: 4px 2px;\n"
                                         "    cursor: pointer;\n"
                                         "    border-radius: 10px; /* 圆角 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                         "}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 0, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.data)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgba(167, 162, 157,100);\n"
                                         "    border: none; /* 无边框 */\n"
                                         "    padding: 10px 20px; /* 内边距 */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font: 12pt \"黑体\";\n"
                                         "    margin: 4px 2px;\n"
                                         "    cursor: pointer;\n"
                                         "    border-radius: 10px; /* 圆角 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                         "}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-xiazai2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon10)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 0, 4, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.data)
        self.dateTimeEdit_2.setStyleSheet("QWidget {\n"
                                          "    background-color: rgba(229, 229, 229, 180); \n"
                                          "    border: 1px solid #ccc; /* 边框 */\n"
                                          "    border-radius: 10px; /* 圆角半径 */\n"
                                          "    padding: 5px; /* 内边距 */\n"
                                         
                                          "}")
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_5.addWidget(self.dateTimeEdit_2, 1, 3, 1, 2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.data)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
                                          "    background-color: #ffffff; /* 白色背景 */\n"
                                          "    color: #333333; /* 文字颜色 */\n"
                                          "    alternate-background-color: #f0f0f0; /* 交替行背景颜色 */\n"
                                          "    selection-background-color: #4AAA50; /* 选中日期背景颜色 */\n"
                                          "    selection-color: white; /* 选中日期文字颜色 */\n"
                                          "    font-size: 14px; /* 字体大小 */\n"
                                          "    border: 1px solid #cccccc; /* 边框 */\n"
                                          "    border-radius: 5px; /* 圆角 */\n"
                                          "}\n"
                                          "\n"
                                          "QCalendarWidget QToolButton {\n"
                                          "    background-color: #ffffff; /* 工具按钮背景颜色 */\n"
                                          "    color: #333333; /* 工具按钮文字颜色 */\n"
                                          "    border: none; /* 无边框 */\n"
                                          "    padding: 5px; /* 内边距 */\n"
                                          "    font-size: 14px; /* 字体大小 */\n"
                                          "}\n"
                                          "\n"
                                          "QCalendarWidget QToolButton::menu-button {\n"
                                          "    subcontrol-origin: padding;\n"
                                          "    subcontrol-position: top right;\n"
                                          "    width: 20px;\n"
                                          "    border-left-width: 1px;\n"
                                          "    border-left-style: solid;\n"
                                          "    border-left-color: #cccccc;\n"
                                          "    border-top-right-radius: 5px;\n"
                                          "    border-bottom-right-radius: 5px;\n"
                                          "    background-color: #ffffff;\n"
                                          "}\n"
                                          "\n"
                                          "QCalendarWidget QToolButton::menu-button:hover {\n"
                                          "    background-color: #f0f0f0; /* 鼠标悬停时的颜色 */\n"
                                          "}\n"
                                          "\n"
                                          "QCalendarWidget QWidget {\n"
                                          "    background-color: #ffffff; /* 子部件背景颜色 */\n"
                                          "    color: #333333; /* 子部件文字颜色 */\n"
                                          "    border: none; /* 无边框 */\n"
                                          "    padding: 5px; /* 内边距 */\n"
                                          "    font-size: 14px; /* 字体大小 */\n"
                                          "}\n"
                                          "\n"
                                          "QCalendarWidget QTableView {\n"
                                          "    background-color: #ffffff; /* 表格背景颜色 */\n"
                                          "    color: #333333; /* 表格文字颜色 */\n"
                                          "    gridline-color: #cccccc; /* 网格线颜色 */\n"
                                          "    selection-background-color: #4CAF50; /* 选中项背景颜色 */\n"
                                          "    selection-color: white; /* 选中项文字颜色 */\n"
                                          "    font-size: 14px; /* 字体大小 */\n"
                                          "    border: 1px solid #cccccc; /* 边框 */\n"
                                          "    border-radius: 5px; /* 圆角 */\n"
                                          "}")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_5.addWidget(self.calendarWidget, 2, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.data)
        self.widget_4.setObjectName("widget_4")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setGeometry(QtCore.QRect(7, 34, 631, 511))
        self.label_6.setStyleSheet("background-color: rgba(117, 117, 117, 105);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.widget_4, 0, 5, 3, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.data)
        self.dateTimeEdit.setStyleSheet("QWidget {\n"
                                        "   background-color: rgba(229, 229, 229, 180); \n"
                                        "    border: 1px solid #ccc; /* 边框 */\n"
                                        "    border-radius: 10px; /* 圆角半径 */\n"
                                        "    padding: 5px; /* 内边距 */\n"
                                       
                                        "}")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_5.addWidget(self.dateTimeEdit, 1, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.data)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.data)
        self.comboBox_4.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_6.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.data)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.data)
        self.comboBox_3.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_6.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.data)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.data)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.data)
        self.comboBox_5.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
        
                                      "}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_6.addWidget(self.comboBox_5, 2, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.data)
        self.comboBox_6.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_6.addWidget(self.comboBox_6, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.data)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.data)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.data)
        self.comboBox_7.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_6.addWidget(self.comboBox_7, 1, 3, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.data)
        self.comboBox_8.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 5px; /* 内边距 */\n"
                                     
                                      "}")
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_6.addWidget(self.comboBox_8, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 3, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.data)
        self.label_13.setStyleSheet("font: 12pt \"黑体\";\n"
                                    "border-radius: 5px; /* 圆角 */\n"
                                    "background-color: rgba(113, 113, 113, 100);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 2, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.gridLayout_5.setColumnStretch(4, 1)
        self.gridLayout_5.setColumnStretch(5, 8)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_5.setRowStretch(2, 3)
        self.gridLayout_5.setRowStretch(3, 1)
        self.stackedWidget.addWidget(self.data)
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.search)
        self.label_5.setStyleSheet("font: 14pt \"等线\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.search)
        self.lineEdit_3.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 10px; /* 内边距 */\n"
                                      "    font: 75 12pt \"Microsoft YaHei UI\";\n"
                                      "}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.search)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgba(167, 162, 157,100);\n"
                                        "    border: none; /* 无边框 */\n"
                                        "    padding: 10px 20px; /* 内边距 */\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font: 16pt \"黑体\";\n"
                                        "    margin: 4px 2px;\n"
                                        "    cursor: pointer;\n"
                                        "    border-radius: 10px; /* 圆角 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                        "}")
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.search)
        self.textBrowser_3.setStyleSheet("QWidget {\n"
                                         "    background-color: rgba(229, 229, 229, 180); \n"
                                         "    border: 1px solid #ccc; /* 边框 */\n"
                                         "    border-radius: 10px; /* 圆角半径 */\n"
                                         "    padding: 10px; /* 内边距 */\n"
                                         "    font: 75 14pt \"Microsoft YaHei \";\n"
                                         "}")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_4.addWidget(self.textBrowser_3, 1, 0, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.search)
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 30, 171, 41))
        self.lineEdit_4.setStyleSheet("QWidget {\n"
                                      "      background-color: rgba(229, 229, 229, 180); \n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 10px; /* 内边距 */\n"
                                      "}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_15 = QtWidgets.QLabel(self.login)
        self.label_15.setGeometry(QtCore.QRect(50, 80, 111, 40))
        self.label_15.setStyleSheet("    font: 12pt \"黑体\";")
        self.label_15.setObjectName("label_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 80, 171, 41))
        self.lineEdit_5.setStyleSheet("QWidget {\n"
                                      "    background-color: rgba(229, 229, 229, 180); /* 背景颜色 */\n"
                                      "    border: 1px solid #ccc; /* 边框 */\n"
                                      "    border-radius: 10px; /* 圆角半径 */\n"
                                      "    padding: 10px; /* 内边距 */\n"
                                      "\n"
                                      "}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_16 = QtWidgets.QLabel(self.login)
        self.label_16.setGeometry(QtCore.QRect(50, 30, 111, 40))
        self.label_16.setStyleSheet("    font: 12pt \"黑体\";")
        self.label_16.setObjectName("label_16")
        self.pushButton_13 = QtWidgets.QPushButton(self.login)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 150, 121, 51))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgba(167, 162, 157,100);\n"
                                         "    border: none; /* 无边框 */\n"
                                         "    padding: 10px 20px; /* 内边距 */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font: 12pt \"黑体\";\n"
                                         "    margin: 4px 2px;\n"
                                         "    cursor: pointer;\n"
                                         "    border-radius: 10px; /* 圆角 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                         "}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("pic/op_png/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon11)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.login)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 150, 121, 51))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
                                         "    background-color: rgba(167, 162, 157,100);\n"
                                         "    border: none; /* 无边框 */\n"
                                         "    padding: 10px 20px; /* 内边距 */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font: 12pt \"黑体\";\n"
                                         "    margin: 4px 2px;\n"
                                         "    cursor: pointer;\n"
                                         "    border-radius: 10px; /* 圆角 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgba(55, 55, 55,80); /* 鼠标悬停时颜色变化 */\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "    background-color: rgba(17, 12, 17,80); /* 按下时颜色变化 */\n"
                                         "}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("pic/op_png/mtiIcon-caozuo-quxiao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon12)
        self.pushButton_14.setObjectName("pushButton_14")
        self.login_info = QtWidgets.QLabel(self.login)
        self.login_info.setGeometry(QtCore.QRect(87, 220, 251, 31))
        self.login_info.setObjectName("login_info")
        self.stackedWidget.addWidget(self.login)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setStyleSheet("background-color: rgba(229, 229, 229, 180); ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "停车场管理系统"))
        self.pushButton_4.setText(_translate("MainWindow", "出场入场"))
        self.pushButton_6.setText(_translate("MainWindow", "车辆查询"))
        self.pushButton_10.setText(_translate("MainWindow", "停 车 位"))
        self.pushButton_5.setText(_translate("MainWindow", "数据分析"))
        self.pushButton_2.setText(_translate("MainWindow", "设    置"))
        self.pushButton.setText(_translate("MainWindow", "登    录"))
        self.label.setText(_translate("MainWindow", "车牌号:"))
        self.pushButton_3.setText(_translate("MainWindow", "入场"))
        self.label_2.setText(_translate("MainWindow", "车牌号:"))
        self.pushButton_7.setText(_translate("MainWindow", "出场"))
        self.label_4.setText(_translate("MainWindow", "扫描此二维码结费出场"))
        self.pushButton_8.setText(_translate("MainWindow", "二维码过期了？点我刷新"))
        self.label_14.setText(_translate("MainWindow", "这是设置界面"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "折扣一"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "折扣二"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "折扣三"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "折扣四"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "白    天"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "黑    夜"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "跟随系统"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "车流量"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "收入"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "停车时长"))
        self.comboBox.setItemText(0, _translate("MainWindow", "折线图"))
        self.comboBox.setItemText(1, _translate("MainWindow", "柱形图"))
        self.pushButton_11.setText(_translate("MainWindow", "预览"))
        self.pushButton_12.setText(_translate("MainWindow", "导出"))
        self.label_8.setText(_translate("MainWindow", "纵轴间隔"))
        self.label_7.setText(_translate("MainWindow", "横轴间隔"))
        self.label_9.setText(_translate("MainWindow", "颜    色"))
        self.label_10.setText(_translate("MainWindow", "test1"))
        self.label_11.setText(_translate("MainWindow", "test2"))
        self.label_12.setText(_translate("MainWindow", "test3"))
        self.label_13.setText(_translate("MainWindow", " ->到->"))
        self.label_5.setText(_translate("MainWindow", "车牌号:"))
        self.pushButton_9.setText(_translate("MainWindow", "查询"))
        self.label_15.setText(_translate("MainWindow", "管理员密码："))
        self.label_16.setText(_translate("MainWindow", "管理员账户："))
        self.pushButton_13.setText(_translate("MainWindow", "登录"))
        self.pushButton_14.setText(_translate("MainWindow", "取消"))
        self.login_info.setText(_translate("MainWindow", "登入管理员账户以生成数据报表"))


import button_rc
